---
- name: Update all packages
  dnf:
    name: "*"
    update_cache: true
    state: latest
    enablerepo:
      - rhel-8-x86_64-appstream
  when: "'dnfupdate' in ansible_run_tags"

- name: check to see if we need a reboot
  command: needs-restarting -r
  register: result
  ignore_errors: yes

- name: display result if we need a reboot
  debug:
    var: result.stdout

# The servers can be rebooted, but it stops the playbook from continuing.

- name: Reboot Server if Necessary
  command: shutdown -r now "Ansible Updates Triggered"
  async: 30
  poll: 0
  when: result.rc == 1
  tags: [ 'dnfupdate', 'never','reboot']

# This pause is mandatory, otherwise the existing control connection
# gets reused!
# (https://gist.github.com/infernix/a968f23c4f4e1d6723e4)
#- name: Pausing to allow server to shutdown and terminate our SSH connection
#  pause: seconds=120
#  when: result.rc == 1
# tags: [ 'dnfupdate', 'never']

#- name: Wait for reboot to complete and SSH to become available
# local_action: wait_for host={{ inventory_hostname }} port=22
#    state=started delay=60 timeout=600
#  retries: 30
#  delay: 30
#  become: true
#  when: result.rc == 1
#  tags: [ 'dnfupdate', 'never']